const items = [
  "All",
  "Office",
  "LivingRoom",
  "Kitchen",
  "Bedroom",
  "Dining",
  "Kids",
];
const colors = [
  { nselected: "#ff7f7f", selected: "#ff0000", name: "red" },
  { nselected: "#7fff7f", selected: "#00ff00", name: "green" },
  { nselected: "#7f7fff", selected: "#3131ff", name: "blue" },
  { nselected: "#7f7f7f", selected: "#0c0c0c", name: "black" },
  { nselected: "#ffdc7f", selected: "#ffba03", name: "yellow" },
];

const products = [
  {
    id: 1,
    itemType: "Office",
    rating: 4,
    available: "In Stock",
    imgs: [
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681753501/react-comfy-store-products/prod-12_ga6sdq.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750048/react-comfy-store-products/iXlbK9A6_o_qohafx.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750129/react-comfy-store-products/A11k7xmf_o_nogovf.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750403/react-comfy-store-products/rPR1K8nP_o_vvlay9.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750506/react-comfy-store-products/extra-4_qmljb3.jpg",
    ],
    img: "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681753501/react-comfy-store-products/prod-12_ga6sdq.jpg",
    price: 30.99,
    camapny: "marcos",
    color: ["red", "blue"],
    name: "Modern Poster",
    detail:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 2,
    itemType: "Bedroom",
    rating: 3,
    available: "In Stock",
    imgs: [
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750929/react-comfy-store-products/product-4_ebl6q1.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750048/react-comfy-store-products/iXlbK9A6_o_qohafx.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750129/react-comfy-store-products/A11k7xmf_o_nogovf.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750403/react-comfy-store-products/rPR1K8nP_o_vvlay9.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750506/react-comfy-store-products/extra-4_qmljb3.jpg",
    ],
    img: "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750929/react-comfy-store-products/product-4_ebl6q1.jpg",
    price: 90.99,
    camapny: "caressa",
    name: "Arm chair",
    color: ["red", "blue", "yellow"],
    detail:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 3,
    itemType: "Kids",
    rating: 3.5,
    available: "In Stock",
    imgs: [
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681753657/react-comfy-store-products/prod-16_jfwx3m.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750048/react-comfy-store-products/iXlbK9A6_o_qohafx.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750129/react-comfy-store-products/A11k7xmf_o_nogovf.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750403/react-comfy-store-products/rPR1K8nP_o_vvlay9.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750506/react-comfy-store-products/extra-4_qmljb3.jpg",
    ],
    img: "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681753657/react-comfy-store-products/prod-16_jfwx3m.jpg",
    price: 960.99,
    camapny: "liddy",
    name: "Suede Armchair",
    color: ["red", "blue", "green"],
    detail:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 4,
    itemType: "Kitchen",
    rating: 2,
    available: "In Stock",
    imgs: [
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681753354/react-comfy-store-products/prod-9_j3dsja.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750048/react-comfy-store-products/iXlbK9A6_o_qohafx.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750129/react-comfy-store-products/A11k7xmf_o_nogovf.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750403/react-comfy-store-products/rPR1K8nP_o_vvlay9.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750506/react-comfy-store-products/extra-4_qmljb3.jpg",
    ],
    img: "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681753354/react-comfy-store-products/prod-9_j3dsja.jpg",
    price: 230.99,
    camapny: "marcos",
    name: "Leather Chair",
    color: ["yellow", "blue"],
    detail:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 5,
    itemType: "Office",
    rating: 4,
    available: "In Stock",
    imgs: [
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681752461/react-comfy-store-products/product-6_rhaxfo.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750048/react-comfy-store-products/iXlbK9A6_o_qohafx.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750129/react-comfy-store-products/A11k7xmf_o_nogovf.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750403/react-comfy-store-products/rPR1K8nP_o_vvlay9.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750506/react-comfy-store-products/extra-4_qmljb3.jpg",
    ],
    img: "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681752461/react-comfy-store-products/product-6_rhaxfo.jpg",
    price: 120.9,
    camapny: "liddy",
    name: "Emperor Bed",
    color: ["red"],
    detail:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 6,
    itemType: "LivingRoom",
    rating: 5,
    available: "In Stock",
    imgs: [
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681749482/react-comfy-store-products/iuYyO9RP_o_upinxq.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750048/react-comfy-store-products/iXlbK9A6_o_qohafx.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750129/react-comfy-store-products/A11k7xmf_o_nogovf.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750403/react-comfy-store-products/rPR1K8nP_o_vvlay9.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750506/react-comfy-store-products/extra-4_qmljb3.jpg",
    ],
    img: "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681749482/react-comfy-store-products/iuYyO9RP_o_upinxq.jpg",
    price: 240.99,
    camapny: "ikea",
    name: "Accent Chair",
    color: ["red", "black"],
    detail:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 7,
    itemType: "Bedroom",
    rating: 4.5,
    available: "In Stock",
    imgs: [
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681753552/react-comfy-store-products/prod-13_cv5csw.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750048/react-comfy-store-products/iXlbK9A6_o_qohafx.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750129/react-comfy-store-products/A11k7xmf_o_nogovf.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750403/react-comfy-store-products/rPR1K8nP_o_vvlay9.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750506/react-comfy-store-products/extra-4_qmljb3.jpg",
    ],
    img: "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681753552/react-comfy-store-products/prod-13_cv5csw.jpg",
    price: 250.99,
    camapny: "caressa",
    name: "Shelf",
    color: ["green", "black"],
    detail:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 8,
    itemType: "Bedroom",
    rating: 3.0,
    available: "In Stock",
    imgs: [
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681753441/react-comfy-store-products/prod-11_lff6yt.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750048/react-comfy-store-products/iXlbK9A6_o_qohafx.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750129/react-comfy-store-products/A11k7xmf_o_nogovf.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750403/react-comfy-store-products/rPR1K8nP_o_vvlay9.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750506/react-comfy-store-products/extra-4_qmljb3.jpg",
    ],
    img: "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681753441/react-comfy-store-products/prod-11_lff6yt.jpg",
    price: 230.99,
    camapny: "ikea",
    name: "Modern Bookshelf",
    color: ["yellow", "black", "red"],
    detail:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
  {
    id: 9,
    itemType: "LivingRoom",
    rating: 2.5,
    available: "In Stock",
    imgs: [
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681753314/react-comfy-store-products/prod-8_qzulqi.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750048/react-comfy-store-products/iXlbK9A6_o_qohafx.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750129/react-comfy-store-products/A11k7xmf_o_nogovf.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750403/react-comfy-store-products/rPR1K8nP_o_vvlay9.jpg",
      "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681750506/react-comfy-store-products/extra-4_qmljb3.jpg",
    ],
    img: "https://res.cloudinary.com/dt2g7mgtv/image/upload/v1681753314/react-comfy-store-products/prod-8_qzulqi.jpg",
    price: 230.99,
    camapny: "marcos",
    color: ["yellow", "black"],
    name: "High-Back Bench",
    detail:
      "Cloud bread VHS hell of banjo bicycle rights jianbing umami mumblecore etsy 8-bit pok pok +1 wolf. Vexillologist yr dreamcatcher waistcoat, authentic chillwave trust fund. Viral typewriter fingerstache pinterest pork belly narwhal. Schlitz venmo everyday carry kitsch pitchfork chillwave iPhone taiyaki trust fund hashtag kinfolk microdosing gochujang live-edge",
  },
];
export { products, items, colors };
